export const data={
 fail:0,
 helpNextPos:[{left:27.37,top:35.33},{left:22.63,top:3.39},{left:54.96,top:39.19},{left:25.56,top:58.42},{left:29.32,top:18.92},
  {left:27.61,top:16.58},{left:24.34,top:24.61},{left:24.54,top:37.76},{left:47.46,top:60.89},{left:63.35,top:58.29}],
 events:{
  'play':'.return-btn',
  'game':'.game-btn',
  'flow':'.videos-btn',
  'map':'.map-btn',
  'bible':'.book-btn',
  'chat':'.chat-btn',
  'loadsave':'.load-save-btn',
  'menu':'.menu-btn',
  'null':'.null-btn',
  'helpNext':'.trash-help-next'
 },
 view:{
  el:'.trash-pop',
  template:'#trash-template',
  activeCls:'active',
  playBtnCls:'play',
  helpBtnCls:'up',
  helpLastCls:'last',
  //shownCls:'shown',
  fsCls:'fs',
  mfsCls:'mfs',
  gamePlayingCls:'game-playing',
  $helpBlock:'.trash-help-item',
  obnul:{
   cls:'null',
   endCls:'null-end',
   afterCls:'null-after',
   dur:'3.3s',
   start:{ep:'9.37s',game:'10.33s',react:'10.66s'},
   waitVid:0,
   srcGood:'',
   srcBad:'',
   href:''
  }
 },
 epProgress:{
  el:'.prog1 .prog-ac'
 },
 gameProgress:{
  el:'.prog2 .prog-ac'
 },
 reactProgress:{
  el:'.prog3 .prog-ac'
 }
};