export const data={
 url:'',
 uid:'',
 copy:'',
 saveReloadTime:2000,
 events:{
  'copy':'.ls-copy-btn',
  'load':'.ls-load-btn',
  'focus':'.ls-load-from',
  'clr':'.ls-clr-btn'
 },
 view:{
  tabCls:'tab-tab',
  el:'.trash-block.loadsave',
  reload:'.reload',
  copyFrom:'.ls-copy-from',
  shownCls:'shown',
  endSaveCls:'ls-load-end',
  errCls:'ls-load-err'
 }
};