export const data={
 soundWait:600,
 dataStart:'choose0',
 data:{},
 /*data:[
  {
   'choose0':{bot:'1',user:[{what:'choose1',text:'a',msg:'a-msg'},{what:'choose2',text:'b',msg:'b-msg'},{what:'choose3',text:'c',msg:'c-msg'}]}
  },
  {
   'choose1':{bot:'1-1',user:[{what:'choose1-1',text:'a-1',msg:'a-1-msg'}]},
   'choose2':{bot:'1-2',user:[{what:'choose2-1',text:'b-1',msg:'b-1-msg'},{what:'choose2-2',text:'b-2',msg:'b-2-msg'}]},
   'choose3':{bot:'1-3',user:[{what:'choose3-1',text:'c-1',msg:'c-1-msg'}]}
  },
  {
   'choose1-1':{bot:'1-1-1',user:[{what:'choose1-1-1',text:'a-1-1',msg:'a-1-1-msg'},{what:'choose1-1-2',text:'a-1-2',msg:'a-1-2-msg'}]},
   'choose2-1':{bot:'1-2-1',user:[{what:'choose2-1-1',text:'b-1-1',msg:'b-1-1-msg'},{what:'choose2-1-2',text:'b-1-2',msg:'b-1-2-msg'},{what:'choose2-1-3',text:'b-1-3',msg:'b-1-3-msg'}]},
   'choose2-2':{bot:'1-2-2',user:[{what:'choose2-2-2',text:'b-2-1',msg:'b-2-1-msg'}]},
   'choose3-1':{bot:'1-3-1',user:[{what:'choose3-1-1',text:'c-1-1',msg:'c-1-1-msg'}]}
  },
  {
   'choose1-1-1':{bot:'1-1-1-1',user:[{what:'',text:'a-1-1-1-stop',msg:'a-1-1-1-stop-msg'}]},
   'choose1-1-2':{bot:'1-1-1-2',user:[{what:'',text:'a-1-2-1-stop',msg:'a-1-2-1-stop-msg'}]},
   'choose2-1-1':{bot:'1-2-1-1',user:[{what:'',text:'b-1-1-1-stop',msg:'b-1-1-1-stop'}]},
   'choose2-1-2':{bot:'1-2-1-2',user:[{what:'',text:'b-1-2-1-stop',msg:'b-1-2-1-stop-msg'}]},
   'choose2-1-3':{bot:'1-2-1-3',user:[{what:'',text:'b-1-3-1-stop',msg:'b-1-3-1-stop-msg'}]},
   'choose2-2-2':{bot:'1-2-2-2',user:[{what:'',text:'b-2-1-1-stop',msg:'b-2-1-1-stop-msg'}]},
   'choose3-1-1':{bot:'1-3-1-1',user:[{what:'',text:'c-1-1-1-stop',msg:'c-1-1-1-stop-msg'}]}
  }],*/
 events:{
  'choose':'.chat-choose'
 },
 view:{
  el:'.trash-block.chat',
  msgBlock:'.chat-wrap',
  msgInto:'.chat-inner',
  chInto:'.chat-ctrls',
  msgTemplate:'#chat-msg-template',
  chTemplate:'#chat-choose-template',
  //$pop:'.bible-pop',
  shownCls:'shown'
 }
};